class AddPeopleFromScraper < ActiveRecord::Migration
  def self.up
    Person.create(first_name: "Wendy", last_name: "Veatch", bio: nil)
    Person.create(first_name: "Tyler", last_name: "Nepote", bio: "Healthy mix of Kevin O'Leary & Mark Cuban")
    Person.create(first_name: "Tim", last_name: "Chase", bio: nil)
    Person.create(first_name: "Thomas", last_name: "Herman", bio: "Odonata Research LLC")
    Person.create(first_name: "Ted", last_name: "Kriwiel", bio: "Helping innovators do what they do.")
    Person.create(first_name: "Ted", last_name: "Kriwiel", bio: "Helping innovators do what they do.")
    Person.create(first_name: "Tall", last_name: "Paul", bio: nil)
    Person.create(first_name: "Susan", last_name: "Lentz", bio: "Connector Extraordinaire")
    Person.create(first_name: "Steve", last_name: "Radley", bio: "Resources for starting or growing your business")
    Person.create(first_name: "Sherry", last_name: "Gegen", bio: "WSU Ventures")
    Person.create(first_name: "Seth", last_name: "Etter", bio: "Full Stack Web Developer", email: nil)
    Person.create(first_name: "Sam", last_name: "Williams", bio: "Team Builder, Coach, Business Guy, Listener, Doer", email: nil)
    Person.create(first_name: "Ryan", last_name: "Tacke", bio: nil, email: nil)
    Person.create(first_name: "Ryan", last_name: "Dahlke", bio: "I help people using web and data technologies.", email: nil)
    Person.create(first_name: "Robin", last_name: "Fertner", bio: "I design things", email: nil)
    Person.create(first_name: "Richard", last_name: "Rierson", bio: "Helping leaders & organizations become more Calm, Confident, Consistent, & Courageous", email: nil)
    Person.create(first_name: "Renee", last_name: "Anderson", bio: "There are vision setters and then there are vision supporters.", email: nil)
    Person.create(first_name: "Nathan", last_name: "Miller", bio: "Strategy, Data, Systems", email: nil)
    Person.create(first_name: "Naomi", last_name: "Shapiro", bio: "Arbiter of fine taste", email: nil)
    Person.create(first_name: "Michael", last_name: "Neth", bio: "Product Design, Game Design, Web Design, Development, Want to fix all the things", email: nil)
    Person.create(first_name: "Michael", last_name: "Aumack", bio: "Finds the resources you don't know you need", email: nil)
    Person.create(first_name: "Matthew", last_name: "Keeler", bio: "There is no system but GNU, and Linux is one of its kernels.", email: nil)
    Person.create(first_name: "Martha", last_name: "Linsner", bio: "I'm a Keeper!", email: nil)
    Person.create(first_name: "Mark", last_name: "Torline", bio: "Center For Entrepreneurship @ Wichita State University", email: nil)
    Person.create(first_name: "Mark", last_name: "Lebbin", bio: nil, email: nil)
    Person.create(first_name: "Marcia", last_name: "Stevens", bio: nil, email: nil)
    Person.create(first_name: "Lyle", last_name: "Mcclanahan", bio: "Proud to be part of the midwest development community!", email: nil)
    Person.create(first_name: "Luke", last_name: "Catlin", bio: "geek by heart, entrepreneur by choice", email: nil)
    Person.create(first_name: "Lee", last_name: "Williams", bio: nil, email: nil)
    Person.create(first_name: "Kylie", last_name: "Stupka", bio: nil, email: nil)
    Person.create(first_name: "Kyle", last_name: "Williams", bio: "Promoter. Instigator. Connector.", email: nil)
    Person.create(first_name: "Kristyn", last_name: "Smith", bio: "I'm not very clever but I design cool things.", email: nil)
    Person.create(first_name: "Kevin", last_name: "Colborn", bio: "Lover of all technology (including high-efficiency washing machines)", email: nil)
    Person.create(first_name: "Kenton", last_name: "Hansen", bio: "People, Startups, Community", email: nil)
    Person.create(first_name: "Keith", last_name: "Wyss", bio: nil, email: nil)
    Person.create(first_name: "Katie", last_name: "Deutsch", bio: "I am a Wichita State University undergraduate students studying Economics and Political Science.", email: nil)
    Person.create(first_name: "Kara", last_name: "Winter", bio: nil, email: nil)
    Person.create(first_name: "Joshua", last_name: "Hensley", bio: nil, email: nil)
    Person.create(first_name: "Josh", last_name: "Cary", bio: nil, email: nil)
    Person.create(first_name: "Jose", last_name: "Ventura-Reyes", bio: "Elite Gaming Championships", email: nil)
    Person.create(first_name: "Jordan", last_name: "Newby", bio: nil, email: nil)
    Person.create(first_name: "Jonathan", last_name: "Van Winkle", bio: "Digital Juggler", email: nil)
    Person.create(first_name: "Jonathan", last_name: "Long", bio: "Catalyst. Not a Complainer", email: nil)
    Person.create(first_name: "Jonathan", last_name: "George", bio: "Moving faster than you.", email: nil)
    Person.create(first_name: "John", last_name: "Martens", bio: "Founder & CEO @NMotionUAS, Firefighter, Entrepreneur", email: nil)
    Person.create(first_name: "John", last_name: "Harrison", bio: nil, email: nil)
    Person.create(first_name: "Jessica", last_name: "Brim", bio: nil, email: nil)
    Person.create(first_name: "Jessica", last_name: "Brim", bio: "Youth Entrepreneurs Student & Alumni Coordinator", email: nil)
    Person.create(first_name: "Jens", last_name: "Torell", bio: "Lets make something!", email: nil)
    Person.create(first_name: "Jeff", last_name: "Darr", bio: nil, email: nil)
    Person.create(first_name: "Jarrett", last_name: "Green", bio: "What's a good tagline?", email: nil)
    Person.create(first_name: "Jamie", last_name: "Hofling", bio: nil, email: nil)
    Person.create(first_name: "Jacqualyn", last_name: "Summervill", bio: "Community instigator. 1/4 stack web developer.", email: nil)
    Person.create(first_name: "Jacob", last_name: "Walker", bio: "Polyglot Software Engineer", email: nil)
    Person.create(first_name: "Jacob", last_name: "Archer", bio: nil, email: nil)
    Person.create(first_name: "Henry", last_name: "Tafolla", bio: nil, email: nil)
    Person.create(first_name: "Gregg", last_name: "Bolinger", bio: "Seth is my hero", email: nil)
    Person.create(first_name: "Grant", last_name: "Mitchell, MD", bio: "Entrepreneur", email: nil)
    Person.create(first_name: "Gilbert", last_name: "galindo", bio: nil, email: nil)
    Person.create(first_name: "Gary", last_name: "Oborny", bio: "Real Estate Developer", email: nil)
    Person.create(first_name: "Gary", last_name: "Mason", bio: nil, email: nil)
    Person.create(first_name: "Gary", last_name: "Schmitt", bio: "Growing Wichita one loan at a time.", email: nil)
    Person.create(first_name: "Erin", last_name: "Blevins", bio: nil, email: nil)
    Person.create(first_name: "Emily", last_name: "Behlmann", bio: "Technology reporter and newbie coder", email: nil)
    Person.create(first_name: "Dominic", last_name: "Greene", bio: nil, email: nil)
    Person.create(first_name: "Dominic", last_name: "Canare", bio: "Maker, educator, altruist", email: nil)
    Person.create(first_name: "Devin", last_name: "Walker", bio: "CEO~Founder at Printpop Visonary~Revolutionary", email: nil)
    Person.create(first_name: "David", last_name: "Mayo", bio: nil, email: nil)
    Person.create(first_name: "Dave", last_name: "Mace", bio: "Technologist, Marketer, Communitarian", email: nil)
    Person.create(first_name: "Daniel", last_name: "James", bio: "Plays with digital legos", email: nil)
    Person.create(first_name: "Cody", last_name: "Saunders", bio: "codysaunders.com", email: nil)
    Person.create(first_name: "Cindy", last_name: "Miles", bio: "Entrepreneur seeking new adventures.", email: nil)
    Person.create(first_name: "Cindy", last_name: "Claycomb", bio: "Bringing Wichita State University innovations and technologies to market", email: nil)
    Person.create(first_name: "Christina", last_name: "Long", bio: "Writer, designer, educator and communications strategist", email: nil)
    Person.create(first_name: "Chad", last_name: "Smith", bio: "Not a drummer.", email: nil)
    Person.create(first_name: "Calvin", last_name: "Nelson", bio: nil, email: nil)
    Person.create(first_name: "Calana", last_name: "Hill", bio: "community manager at The Labor Party", email: nil)
    Person.create(first_name: "Bruce", last_name: "Rowley", bio: "Entrepreneur. Dad. Traveller. Marketer.", email: nil)
    Person.create(first_name: "Brian", last_name: "Simpson", bio: "No one needs a tagline.", email: nil)
    Person.create(first_name: "Brian", last_name: "Buller", bio: nil, email: nil)
    Person.create(first_name: "Brandon", last_name: "Paulseen", bio: "Clear thinking leads to feeling deeply and acting consistently", email: nil)
    Person.create(first_name: "Bill", last_name: "Ramsey", bio: "Tech lover, entrepreneur", email: nil)
    Person.create(first_name: "Barrett", last_name: "Morgan", bio: "I'm a designer, love the outdoors, and build Drupal sites.", email: nil)
    Person.create(first_name: "Austin", last_name: "Calvert", bio: "Entrepreneur, Designer (IOS applications)", email: nil)
    Person.create(first_name: "Anne", last_name: "Dewvall", bio: nil, email: nil)
    Person.create(first_name: "Alex", last_name: "Wespi", bio: "Social Media Buff", email: nil)
    Person.create(first_name: "Alex", last_name: "Wernli", bio: nil, email: nil)
    Person.create(first_name: "Alex", last_name: "Twitchel", bio: "Designer in the City.", email: nil)
    Person.create(first_name: "Aaron", last_name: "Wirtz", bio: nil, email: nil)
    Person.create(first_name: "Aaron", last_name: "Walker", bio: nil, email: nil)
  end

  def self.down
  end
end
